import sqlite3
from datetime import datetime

DB_PATH = "database/properties.db"

def init_table():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS nhis_informal_settlements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            region TEXT,
            local_authority TEXT,
            settlement_name TEXT,
            is_profiled TEXT,
            is_planned TEXT,
            is_surveyed TEXT,
            land_ownership TEXT,
            tenure_security TEXT,
            number_of_erven TEXT,
            congestion_status TEXT,
            communal_facilities TEXT,
            bulk_services TEXT,
            upgrade_level INTEGER,
            date_loaded TEXT
        )
    """)
    conn.commit()
    conn.close()

ALL_SETTLEMENTS = [
    ("//Kharas","Aroab","Sonop","No","Yes","Yes","Local Authority","Leasehold","240","Decongested","Communal tap, toilets, electricity high mast light","Not Applicable",1),
    ("//Kharas","Berseba","Extension 1 DC Goliath","No","No","No","Local Authority","Freehold","174","Decongested","Communal toilets","Water, Electricity",3),
    ("//Kharas","Berseba","Extension 2 Steinkorph","No","No","No","Local Authority","Freehold","233","Decongested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Berseba","Extension 3 Brukkaros","No","No","No","Local Authority","Freehold","127","Decongested","Communal tap, toilets","Water, Electricity",3),
    ("//Kharas","Berseba","Extension 4 Brukkaros","No","No","No","Local Authority","Freehold","162","Decongested","Communal tap, toilets","Water, Electricity",3),
    ("//Kharas","Berseba","Extension 5 Palmlaagte","No","No","No","Local Authority","Freehold","287","Decongested","None","Water, Sewer, Electricity",4),
    ("//Kharas","Bethanie","Gobebfontein Extension 2","Yes","Yes","Yes","Local Authority","Freehold","254","Decongested","None","Water, Sewer",3),
    ("//Kharas","Bethanie","Riverside Extension 2","No","Yes","No","Local Authority","Freehold","150","Decongested","None","Water, Sewer",3),
    ("//Kharas","Bethanie","Schemelendorf Extension 2","Yes","Yes","Yes","Local Authority","Freehold","95","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Koes","Koes Extension 1","No","Yes","Yes","Local Authority","Freehold","109","Decongested","None","Not Applicable",1),
    ("//Kharas","Koes","Koes Extension 3","No","Yes","Yes","Local Authority","Freehold","19","Decongested","None","Water, Electricity, Roads",4),
    ("//Kharas","Koes","Donkerhoek","No","No","No","Local Authority","No Tenure Security","1","Decongested","None","Road",2),
    ("//Kharas","Luderitz","Amilema","Yes","Yes","No","Local Authority","Certificate of Occupancy","600","Congested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Luderitz","Area 7","Yes","Yes","No","Local Authority","Certificate of Occupancy","228","Congested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Luderitz","Sand Hotel","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Luderitz","Old Location","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Oranjemund","Swartkops Portion 12","No","No","No","Local Authority","Leasehold","1","Congested","Communal tap, toilets","Water, Sewer, Electricity",4),
    ("//Kharas","Tses","Growwerand South","No","Yes","No","Local Authority","Leasehold","503","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Tses","Jamaica Extension 1","No","Yes","No","Local Authority","Leasehold","346","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("//Kharas","Tses","Soutput North Extension 4","No","Yes","No","Local Authority","Leasehold","277","Decongested","None","Sewer, Electricity",3),
    ("//Kharas","Tses","Soutput South Extension 5","No","Yes","No","Local Authority","Leasehold","168","Decongested","None","Water, Sewer, Electricity",4),
    ("//Kharas","Keetmanshoop","Brukharos Extension 1","No","No","Yes","Local Authority","Certificate of Occupancy","30","Decongested","None","Not Applicable",1),
    ("//Kharas","Keetmanshoop","Brukharos Extension 2","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","212","Decongested","Communal tap","Water, Sewer",3),
    ("//Kharas","Keetmanshoop","Brukharos Extension 3","No","No","Yes","Local Authority","Certificate of Occupancy","222","Decongested","Communal tap","Water",2),
    ("//Kharas","Keetmanshoop","Brukharos Extension 4","No","No","Yes","Local Authority","Certificate of Occupancy","250","Decongested","None","Not Applicable",1),
    ("//Kharas","Keetmanshoop","Tseiblaagte Extension 7","Yes","Yes","Yes","Local Authority","Leasehold","297","Congested","Communal tap","Water, Sewer, Electricity",4),
    ("Erongo","Arandis","Rossing Heights Proper","No","Yes","Yes","Local Authority","Leasehold","284","Decongested","None","Not Applicable",1),
    ("Erongo","Hentiesbay","!Goas","Yes","Yes","Yes","Local Authority","Leasehold","172","Congested","Communal tap","Water, Sewer, Electricity",4),
    ("Erongo","Karibib","Harambe Extension 7","Yes","Yes","Yes","Local Authority","Freehold","347","Decongested","None","Water, Sewer, Electricity",4),
    ("Erongo","Karibib","Harambe Extension 8","Unknown","Yes","Yes","Local Authority","Freehold","339","Decongested","Communal tap","Water",2),
    ("Erongo","Karibib","Harambe Extension 9","Unknown","Yes","Yes","Local Authority","Freehold","339","Congested","Communal tap","Water",2),
    ("Erongo","Karibib","New Location","Unknown","Yes","Yes","Local Authority","Freehold","165","Decongested","None","Not Applicable",1),
    ("Erongo","Karibib","Old Location","Unknown","Yes","Yes","Local Authority","Freehold","324","Decongested","None","Not Applicable",1),
    ("Erongo","Karibib","Usab Informal Settlement","Yes","Yes","Yes","Local Authority","Freehold","717","Decongested","None","Water, Sewer, Electricity",4),
    ("Erongo","Omaruru","7de Laan Extension 8","Yes","Yes","Yes","Local Authority","Freehold","643","Decongested","Communal tap","Electricity",2),
    ("Erongo","Omaruru","7de Laan Extension 9","Yes","Yes","Yes","Local Authority","Freehold","643","Decongested","Communal tap","Electricity",2),
    ("Erongo","Swakopmund","3 Housing Groups A","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","283","Decongested","None","Not Applicable",1),
    ("Erongo","Swakopmund","3 Housing Groups B","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","313","Decongested","None","Not Applicable",1),
    ("Erongo","Swakopmund","DRC Airport","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","314","Congested","Communal tap","Not Applicable",1),
    ("Erongo","Usakos","Onguluumbashe","Yes","Yes","Yes","Local Authority","Leasehold","442","Congested","Communal tap","Water, Electricity",3),
    ("Erongo","Usakos","Erongosig Extension 2","No","No","Yes","Local Authority","Leasehold","9999","Decongested","Communal tap","Water, Sewer",3),
    ("Erongo","Usakos","Erongosig Extension 3","No","No","Yes","Local Authority","Leasehold","9999","Decongested","Communal tap","Water, Sewer",3),
    ("Erongo","Usakos","Saamstaan","Yes","Yes","Yes","Local Authority","Leasehold","220","Congested","Communal tap","Water, Sewer",3),
    ("Hardap","Aranos","Bosduin","No","Yes","Yes","Local Authority","Landhold","60","Decongested","Communal tap","Water, Electricity",3),
    ("Hardap","Aranos","Valpos","No","Yes","No","Local Authority","Landhold","0","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Aranos","Vee pos","No","Yes","No","Local Authority","Landhold","188","Decongested","Communal tap","Not Applicable",1),
    ("Hardap","Aranos","Nuwerus","No","Yes","Yes","Local Authority","Landhold","9999","Decongested","Communal tap","Water, Electricity",3),
    ("Hardap","Aranos","Sonora Extension 1","No","No","No","Local Authority","Landhold","9999","Decongested","None","Water, Electricity",3),
    ("Hardap","Gibeon","Sunrise","Yes","Yes","No","Local Authority","Certificate of Occupancy","0","Decongested","Communal tap","Not Applicable",1),
    ("Hardap","Gochas","Gomxab Naus","No","No","No","Local Authority","Leasehold","9999","Decongested","Communal tap","Water",1),
    ("Hardap","Maltahohe","Blikkies Dorp","Yes","Yes","Yes","Local Authority","Leasehold","9999","Decongested","Communal tap","Electricity",2),
    ("Hardap","Maltahohe","Vaal Kamp","Yes","Yes","Yes","Local Authority","Leasehold","9999","Decongested","Communal tap","Electricity",2),
    ("Hardap","Rehoboth","Bahnhoff","No","Yes","Yes","Local Authority","Freehold","239","Decongested","Communal tap, electricity high mast light","Not Applicable",1),
    ("Hardap","Rehoboth","Block F Burgershoek","Yes","Yes","No","Local Authority","No Tenure Security","1103","Decongested","Communal tap","Not Applicable",1),
    ("Hardap","Rehoboth","Block E Blikkiesdorp Extension 3","Yes","Yes","Yes","Local Authority","Freehold","282","Decongested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Rehoboth","Block E Blikkiesdorp Extension 4","Yes","Yes","Yes","Local Authority","Freehold","392","Decongested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Rehoboth","Block E Blikkiesdorp Extension 5","Yes","Yes","Yes","Local Authority","Freehold","361","Decongested","Communal tap, toilets","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Rehoboth","Block H Rooiduine Extension 3","Yes","Yes","No","Local Authority","Landhold","884","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Rehoboth","Block H Rooiduine Extension 4","Yes","Yes","No","Local Authority","Landhold","884","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Rehoboth","Block H Rooiduine Extension 5","Yes","Yes","No","Local Authority","Landhold","884","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Rehoboth","Block H Rooiduine Extension 6","Yes","Yes","No","Local Authority","Landhold","884","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Rehoboth","Block F Volstruis Vlakte","Yes","Yes","No","Local Authority","No Tenure Security","571","Decongested","Communal tap","Not Applicable",1),
    ("Hardap","Stampriet","Build Together Houses","No","Yes","No","Local Authority","Certificate of Occupancy","130","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Stampriet","Other Informal Settlements","No","No","No","Local Authority","Certificate of Occupancy","842","Congested","Communal tap","Water, Electricity",3),
    ("Hardap","Stampriet","Shack Dweller Houses","No","Yes","No","Local Authority","Certificate of Occupancy","45","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Kalkrand","Donkerhoek and Papagai","Unknown","Yes","Yes","Local Authority","Leasehold","221","Congested","Communal toilets","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Kalkrand","Vyf Rand","Unknown","Unknown","No","Local Authority","Leasehold","60","Decongested","Communal tap","Not Applicable",1),
    ("Hardap","Kalkrand","Papagaai","Unknown","Unknown","No","Local Authority","Leasehold","67","Congested","Communal tap","Water, Sewer, Electricity, Roads",5),
    ("Hardap","Mariental","Empelheim Extension 5","No","Yes","Yes","Local Authority","Landhold","750","Congested","Communal tap","Not Applicable",2),
    ("Hardap","Mariental","Aimablaagte Proper Donkerhoek","Yes","Yes","Yes","Local Authority","Landhold","82","Congested","Communal tap","Electricity",2),
    ("Hardap","Mariental","Aimablaagte Proper Ombili","Yes","Yes","Yes","Local Authority","Landhold","0","Congested","Communal tap","Electricity",2),
    ("Hardap","Mariental","Aimablaagte Proper Oshiwana Penduka","Yes","Yes","Yes","Local Authority","Landhold","50","Congested","Communal tap","Sewer, Electricity",3),
    ("Hardap","Mariental","Aimablaagte Extension 3 Own Risk","Yes","Yes","Yes","Local Authority","Landhold","303","Congested","Communal tap","Not Applicable",1),
    ("Hardap","Mariental","Aimablaagte Ombili Own Risk","Yes","Yes","Yes","Local Authority","Landhold","207","Congested","Communal tap","Not Applicable",1),
    ("Kavango East","Divundu","Divundu Extension 5","No","Yes","No","Local Authority","Freehold","9999","Decongested","None","Not Applicable",1),
    ("Kavango East","Divundu","Divundu Extension 6","No","Yes","No","Local Authority","Freehold","9999","Decongested","None","Not Applicable",1),
    ("Kavango East","Rundu","Donkerhoek","No","Yes","Yes","Local Authority","Leasehold","219","Congested","None","Water, Sewer, Electricity",4),
    ("Kavango East","Rundu","Kaisosi Formal A","No","Yes","Yes","Local Authority","Leasehold","0","Congested","None","Water, Electricity",3),
    ("Kavango East","Rundu","Kaisosi Formal B","No","Yes","Yes","Local Authority","Leasehold","0","Congested","None","Water, Electricity",3),
    ("Kavango East","Rundu","Masivi","No","No","No","Local Authority","Freehold","250","Decongested","Communal tap","Water",2),
    ("Kavango East","Rundu","Ndama Informal A","No","Yes","Yes","Local Authority","Freehold","0","Congested","Communal tap","Water, Electricity",3),
    ("Kavango East","Rundu","Ndama Informal B","No","Yes","Yes","Local Authority","Freehold","0","Congested","Communal tap","Water, Electricity",3),
    ("Kavango East","Rundu","Ndama Informal C","No","Yes","Yes","Local Authority","Freehold","0","Congested","Communal tap","Water, Electricity",3),
    ("Kavango East","Rundu","Ngwangwa","No","No","No","Local Authority","Freehold","250","Decongested","Borehole","Not Applicable",1),
    ("Kavango East","Rundu","Satotwa","No","No","No","Local Authority","Freehold","2000","Congested","Communal tap","Not Applicable",1),
    ("Kavango East","Rundu","Sauyemwa A","No","Yes","Yes","Local Authority","Freehold","0","Congested","None","Water, Electricity",3),
    ("Kavango East","Rundu","Sauyemwa B","No","Yes","Yes","Local Authority","Freehold","0","Congested","None","Water, Electricity",3),
    ("Kavango East","Rundu","Sikanduko","No","Yes","No","Local Authority","Freehold","2550","Decongested","Communal tap","Water, Electricity",3),
    ("Kavango East","Rundu","Tuhingereni","No","No","No","Local Authority","Freehold","16750","Congested","Communal tap","Not Applicable",1),
    ("Kavango East","Rundu","Tumweneni South","No","No","No","Local Authority","Freehold","5270","Decongested","Borehole","Not Applicable",1),
    ("Kavango East","Rundu","Kaisosi West Informal","No","No","No","Local Authority","No Tenure Security","9999","Congested","None","Not Applicable",1),
    ("Kavango East","Rundu","Kaisosi East Informal","No","No","No","Local Authority","No Tenure Security","9999","Congested","None","Not Applicable",1),
    ("Kavango East","Rundu","Tumweneni North","No","No","No","Local Authority","Freehold","9999","Congested","None","Not Applicable",1),
    ("Kavango West","Nkurenkuru","Kahenge Extension 7","No","Yes","Yes","Local Authority","Freehold","314","Decongested","None","Not applicable",1),
    ("Kavango West","Nkurenkuru","Nkurenkuru Extension 10","No","Yes","Yes","Local Authority","Leasehold","323","Decongested","None","Electricity",2),
    ("Kavango West","Nkurenkuru","Nkurenkuru Extension 13","No","Yes","Yes","Local Authority","Leasehold","253","Decongested","None","Not applicable",1),
    ("Kavango West","Nkurenkuru","Nkurenkuru Extension 14","No","Yes","Yes","Local Authority","Leasehold","330","Decongested","None","Electricity",2),
    ("Kavango West","Nkurenkuru","Nkurenkuru Extension 8","No","Yes","Yes","Local Authority","Freehold","281","Decongested","None","Not applicable",1),
    ("Khomas","Windhoek","Abraham Iiyambo KAP","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","B Police Station MG","Yes","No","Yes","Local Authority","Certificate of Occupancy","0","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Beijing Street BA","Yes","No","No","Local Authority","No Tenure Security","0","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","Brenden Simbwaye A","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Brenden Simbwaye B","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Brenden Simbwaye C","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Brenden Simbwaye D","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Brenden Simbwaye F","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal tap, toilets, electricity high mast light","Not Applicable",1),
    ("Khomas","Windhoek","Cuba Erf 551","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Daan Viljoen DA","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Desperate for Shelter DS","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","9999","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","Fransina Kahungu","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Ganzi Area GA","Yes","Yes","No","Local Authority","No Tenure Security","9999","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","Helvi Kondombolo","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Kilimandjaro KLM","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Mandume Ndemufayo","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","Okahandja Park A","Yes","No","No","Local Authority","Certificate of Occupancy","0","Congested","Communal toilets","Not Applicable",1),
    ("Khomas","Windhoek","Okahandja Park D","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Okandundu","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Okatunda","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets, electricity high mast light","Not Applicable",1),
    ("Khomas","Windhoek","One Nation A-B","Yes","No","Yes","Local Authority","Certificate of Occupancy","0","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","One Nation No.1","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets, electricity high mast light","Not Applicable",1),
    ("Khomas","Windhoek","Onghuwo Yepongo","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Ongulumbashe No.1 and 2","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Onyika No. 1","Yes","Yes","Yes","Local Authority","No Tenure Security","9999","Congested","Communal toilets","Not Applicable",1),
    ("Khomas","Windhoek","Brakwater Mix Extension 1","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Brakwater Mix Proper","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","85","Congested","Communal tap, toilets, electricity high mast light","Not Applicable",1),
    ("Khomas","Windhoek","Samuel Maharero","Yes","Yes","Yes","Local Authority","Certificate of Occupancy","9999","Congested","None","Not Applicable",1),
    ("Khomas","Windhoek","Peter Nanyemba A","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap, toilets","Not Applicable",1),
    ("Khomas","Windhoek","Thlabanero A","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap","Not Applicable",1),
    ("Khomas","Windhoek","Toring TA","Yes","Yes","No","Local Authority","Certificate of Occupancy","9999","Congested","Communal tap","Not Applicable",1),
    ("Kunene","Kamanjab","Newland Reception Area","No","No","No","Local Authority","Certificate of Occupancy","0","Decongested","None","Not Applicable",1),
    ("Kunene","Kamanjab","Rotsvesting Extension 4","No","Yes","No","Local Authority","Leasehold","159","Decongested","None","Water, Sewer, Electricity",4),
    ("Kunene","Kamanjab","Rotsvesting Extension 5","No","Yes","No","Local Authority","Leasehold","197","Decongested","None","Water, Sewer, Electricity",4),
    ("Kunene","Kamanjab","Rotsvesting Extension 6","No","Yes","No","Local Authority","Landhold","400","Decongested","None","Water, Sewer, Electricity",4),
    ("Kunene","Khorixas","Ada Naugu No.1","Yes","Yes","Yes","Local Authority","Freehold","229","Decongested","Communal tap","Water, Electricity",3),
    ("Kunene","Khorixas","Ada Naugu No.2","Yes","Yes","Yes","Local Authority","Freehold","461","Decongested","Communal tap","Water",2),
    ("Kunene","Khorixas","Donkerhoek 11","Yes","Yes","Yes","Local Authority","Freehold","300","Decongested","Communal tap","Water, Electricity",3),
    ("Kunene","Khorixas","Donkerhoek 12","Yes","Yes","Yes","Local Authority","Freehold","318","Decongested","Communal tap","Water, Electricity",3),
    ("Kunene","Opuwo","New Katutura","Yes","Yes","Yes","Local Authority","Leasehold","9999","Decongested","None","Water, Sewer, Electricity",4),
    ("Kunene","Opuwo","Old Katutura","Yes","Yes","Yes","Local Authority","Leasehold","9999","Decongested","None","Water, Sewer, Electricity",4),
    ("Kunene","Opuwo","Orutjandja North","Yes","Yes","No","Partly communal","Leasehold","1927","Congested","None","Water, Electricity",3),
    ("Kunene","Opuwo","Orutjandja South","Yes","No","No","Local Authority","Leasehold","0","Congested","None","Water, Electricity",3),
    ("Kunene","Opuwo","Otjorungondo","Yes","Yes","Yes","Partly communal","Leasehold","281","Congested","Communal water tank","Not Applicable",1),
    ("Kunene","Outjo","7 de Laan","Yes","No","No","Local Authority","Leasehold","392","Congested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Camp 4","Yes","No","No","Local Authority","Leasehold","180","Congested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Camp 5","Yes","No","No","Local Authority","Leasehold","242","Congested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Ehangano","Yes","Yes","Yes","Local Authority","Leasehold","991","Decongested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Extension 8","No","Yes","Yes","Local Authority","Leasehold","460","Decongested","Communal tap","Not Applicable",1),
    ("Kunene","Outjo","Extension 9","No","Yes","No","Local Authority","Leasehold","2400","Decongested","Communal tap","Not Applicable",1),
    ("Kunene","Outjo","Kap en Bou","Yes","Yes","Yes","Local Authority","Leasehold","765","Congested","Communal tap","Not Applicable",1),
    ("Kunene","Outjo","Saamstaan 1","No","Yes","Yes","Local Authority","Leasehold","40","Decongested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Saamstaan 2","No","Yes","No","Local Authority","Leasehold","69","Decongested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Soweto","Yes","No","No","Local Authority","Leasehold","188","Congested","Communal tap","Electricity",2),
    ("Kunene","Outjo","Urib Township","No","Yes","Yes","Local Authority","Leasehold","931","Decongested","Communal tap","Not Applicable",1),
    ("Ohangwena","Eenhana","Ekolola Reception","Yes","Yes","No","Local Authority","Leasehold","600","Decongested","None","Water, Sewer",3),
    ("Ohangwena","Eenhana","Ombili","Yes","No","No","Local Authority","No Tenure Security","9999","Unknown","None","Not applicable",1),
    ("Ohangwena","Eenhana","Ouholamo","No","No","No","Local Authority","No Tenure Security","9999","Unknown","Communal tap","Not Applicable",1),
    ("Ohangwena","Eenhana","Oukango Park","Yes","Yes","Yes","Local Authority","Leasehold","316","Decongested","None","Water, Sewer, Electricity, Roads",5),
    ("Ohangwena","Helao Nafidi","Bonya Extension 7","Yes","No","No","Local Authority","Leasehold","0","Congested","Communal tap","Not applicable",1),
    ("Ohangwena","Helao Nafidi","Location 17 Oshikango Extension 4","Yes","Yes","Yes","Local Authority","Leasehold","403","Decongested","None","Water",2),
    ("Ohangwena","Helao Nafidi","Ohangwena Location","Yes","No","No","Local Authority","Leasehold","166","Decongested","None","Water, Electricity",3),
    ("Ohangwena","Helao Nafidi","Olunghono Extension 1","Yes","Yes","Yes","Local Authority","Leasehold","194","Decongested","None","Water, Electricity",3),
    ("Ohangwena","Helao Nafidi","Ombili Oukango Park Extension 2","Yes","No","No","Local Authority","Leasehold","0","Congested","Communal tap","Not applicable",1),
    ("Ohangwena","Helao Nafidi","Ondigwanyama","No","No","No","Local Authority","Leasehold","0","Congested","None","Water, Electricity",3),
    ("Ohangwena","Helao Nafidi","Oshikango Extension 1","Yes","Yes","Yes","Local Authority","Leasehold","162","Decongested","None","Water, Electricity",3),
    ("Ohangwena","Helao Nafidi","Oshikango Extension 7","Yes","Yes","Yes","Local Authority","Leasehold","303","Decongested","None","Water, Electricity",3),
    ("Ohangwena","Okongo","Area Behind Picknpay","No","No","No","Local Authority","No Tenure Security","0","Congested","None","Not applicable",1),
    ("Ohangwena","Okongo","New Reception Area","Yes","Yes","Yes","Local Authority","Leasehold","1807","Decongested","Communal toilets","Water, Sewer, Roads",4),
    ("Omaheke","Gobabis","Freedom Square Epako","Yes","Yes","Yes","Private Owned","Landhold","290","Decongested","None","Water, Sewer",3),
    ("Omaheke","Gobabis","Kanaan A Epako","No","No","No","Local Authority","Leasehold","1208","Decongested","Communal tap","Water, Sewer, Electricity",4),
    ("Omaheke","Gobabis","Kanaan B Epako","No","No","No","Local Authority","Leasehold","296","Decongested","Communal tap","Not Applicable",1),
    ("Omaheke","Gobabis","Kanaan C Epako","Yes","No","Yes","Local Authority","Leasehold","9999","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Gobabis","Tuerijandjera","Yes","Yes","Yes","Local Authority","Leasehold","9999","Congested","None","Water, Sewer",3),
    ("Omaheke","Gobabis","Solar Sunrise","No","No","No","Private Owned","Leasehold","9999","Congested","None","Not Applicable",1),
    ("Omaheke","Gobabis","Nossobville","No","No","No","Local Authority","Leasehold","9999","Congested","None","Not Applicable",1),
    ("Omaheke","Leonardville","Amraalsduin Extension 1","No","Yes","No","Local Authority","Leasehold","9999","Decongested","Communal tap","Water, Electricity",3),
    ("Omaheke","Leonardville","Amraalsduin Extension 2","No","No","No","Local Authority","Leasehold","9999","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Ozohambo Block A","Yes","Yes","Yes","Local Authority","No Tenure Security","249","Decongested","None","Water, Sewer, Electricity",4),
    ("Omaheke","Otjinene","Ozohambo Block B","Yes","Yes","Yes","Local Authority","No Tenure Security","273","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Ozohambo Block C","Yes","Yes","No","Local Authority","No Tenure Security","94","Congested","None","Not Applicable",1),
    ("Omaheke","Otjinene","Old Power Station","No","No","No","Local Authority","No Tenure Security","1","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Okatauriro","No","No","No","Local Authority","No Tenure Security","1","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Okarokape","No","No","No","Local Authority","No Tenure Security","1","Decongested","None","Not Applicable",1),
    ("Omaheke","Otjinene","Otjiramba","No","No","No","Local Authority","No Tenure Security","1","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Kahitira","No","No","No","Local Authority","No Tenure Security","9999","Congested","Communal tap","Not Applicable",1),
    ("Omaheke","Otjinene","Stanvas","No","No","No","Local Authority","No Tenure Security","1","Decongested","Communal tap","Not Applicable",1),
    ("Omaheke","Witvlei","Premises","No","Yes","No","Local Authority","Leasehold","63","Congested","None","Water",2),
    ("Omaheke","Witvlei","Omataura Section 72","No","No","No","Local Authority","Leasehold","60","Decongested","Communal tap","Not Applicable",1),
    ("Omaheke","Witvlei","Omataura Section 77","No","Yes","No","Local Authority","Leasehold","244","Decongested","Communal tap","Not Applicable",1),
    ("Omaheke","Witvlei","Omataura Extension 2","No","Yes","Yes","Local Authority","Leasehold","447","Decongested","Communal tap","Water, Roads",3),
    ("Omusati","Okahao","Kashenda Extension 3","No","Yes","Yes","Local Authority","Freehold","207","Decongested","Unknown","Water",2),
    ("Omusati","Okahao","Omakeendali","No","No","No","Local Authority","Starter","9999","Decongested","Communal tap, toilets","Electricity",2),
    ("Omusati","Okahao","Opig Station","No","Yes","Yes","Local Authority","Starter","25","Decongested","Unknown","Electricity",2),
    ("Omusati","Outapi","Nakayale Extension 2","Yes","Yes","Yes","Local Authority","Freehold","301","Unknown","Unknown","Water",2),
    ("Omusati","Ruacana","Okondeka","No","No","No","Local Authority","Leasehold","350","Decongested","None","Water, Sewer, Electricity",4),
    ("Omusati","Ruacana","Omonawatjihozu A","No","Yes","No","Local Authority","Leasehold","300","Decongested","None","Water, Sewer, Electricity",4),
    ("Omusati","Ruacana","Omonawatjihozu B","No","Yes","No","Local Authority","Leasehold","300","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Okangwena A","No","Yes","Yes","Local Authority","Leasehold","262","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Okangwena B","No","Yes","Yes","Local Authority","Leasehold","262","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Omakulukuma","No","Yes","Yes","Local Authority","Leasehold","401","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Omashaka 1","No","Yes","Unknown","Local Authority","Leasehold","709","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Omashaka 2","No","Yes","Yes","Local Authority","Leasehold","824","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Omashaka gakakondo A","No","Yes","Yes","Local Authority","Leasehold","350","Decongested","None","Water, Electricity",3),
    ("Oshana","Ondangwa","Omashaka gakakondo B","No","Yes","Yes","Local Authority","Leasehold","0","Congested","None","Water",2),
    ("Oshana","Ondangwa","Onantsi A","No","Yes","Yes","Local Authority","Leasehold","340","Decongested","None","Water, Electricity",3),
    ("Oshana","Ondangwa","Onantsi B","No","Yes","Yes","Local Authority","Leasehold","232","Decongested","None","Water, Electricity",3),
    ("Oshana","Ondangwa","Uupopo","No","Yes","Yes","Local Authority","Leasehold","272","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ondangwa","Uupopo Epya","No","Yes","Yes","Local Authority","Leasehold","96","Congested","None","Water, Electricity",3),
    ("Oshana","Ongwediva","Benjamin Shiteni","No","Yes","Yes","Local Authority","Freehold","141","Decongested","None","Water",2),
    ("Oshana","Ongwediva","Efidi Extension 2","No","Yes","Yes","Local Authority","Freehold","322","Decongested","None","Water, Electricity",3),
    ("Oshana","Ongwediva","Efidi Extension 5","No","Yes","Yes","Local Authority","Freehold","168","Decongested","None","Water, Electricity",3),
    ("Oshana","Ongwediva","Omatando Extension 8","No","Yes","Yes","Local Authority","Freehold","48","Decongested","None","Water, Electricity",3),
    ("Oshana","Ongwediva","Sky Phase 1","No","No","Yes","Local Authority","Leasehold","309","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshana","Ongwediva","Sky Phase 2","No","No","Yes","Local Authority","Leasehold","214","Decongested","None","Water, Electricity",3),
    ("Oshana","Ongwediva","Sky Phase 3","No","No","Yes","Local Authority","Leasehold","152","Decongested","None","Water, Electricity",3),
    ("Oshana","Oshakati","Evululuko Phase 3","No","Yes","No","Local Authority","Leasehold","325","Congested","None","Water",2),
    ("Oshana","Oshakati","Uupindi South","No","Yes","No","Local Authority","Leasehold","231","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Uupindi North","No","Yes","No","Local Authority","Leasehold","231","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Okandjengedi South Extension 1","No","Yes","No","Local Authority","Leasehold","231","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Okandjengedi South Extension 2","No","No","No","Local Authority","Leasehold","150","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Okandjengedi North","No","No","No","Local Authority","Leasehold","150","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Okandjengedi North Extension 1","No","No","No","Local Authority","Leasehold","150","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Okandjengedi North Extension 2","No","No","No","Local Authority","Leasehold","150","Decongested","None","Water, Electricity, Roads",4),
    ("Oshana","Oshakati","Oshakati Extension 11","No","Yes","No","Local Authority","Leasehold","252","Decongested","None","Water",2),
    ("Oshana","Oshakati","Oshakati Extension 12","No","Yes","No","Local Authority","Leasehold","228","Decongested","None","Water",2),
    ("Oshana","Oshakati","Oshakati Extension 13","No","Yes","Yes","Local Authority","Leasehold","234","Decongested","None","Water",2),
    ("Oshana","Oshakati","Uupindi North Phase 2","No","Yes","No","Local Authority","Leasehold","326","Congested","None","Water",2),
    ("Oshana","Oshakati","Uupindi South Phase 2","No","Yes","No","Local Authority","Leasehold","193","Congested","None","Water",2),
    ("Oshikoto","Omuthiya","Kaniita","Yes","Yes","Yes","Local Authority","Leasehold","9999","Congested","Communal tap, toilets, electricity high mast light","Water, Electricity",3),
    ("Oshikoto","Oniipa","Extension 3","No","Yes","Yes","Local Authority","Leasehold","271","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions K","No","No","No","Local Authority","Leasehold","288","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions L","No","No","No","Local Authority","Leasehold","223","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions N","No","No","No","Local Authority","Leasehold","332","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions O","No","No","No","Local Authority","Leasehold","298","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions P","No","No","No","Local Authority","Leasehold","327","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions Q","No","No","No","Local Authority","Leasehold","258","Congested","None","Water, Electricity",3),
    ("Oshikoto","Oniipa","Onethindi Portions R","No","No","No","Local Authority","Leasehold","298","Congested","None","Water, Electricity",3),
    ("Oshikoto","Tsumeb","Kuvukiland Block C","Yes","Yes","No","Local Authority","Leasehold","716","Decongested","Communal tap","Not Applicable",1),
    ("Oshikoto","Tsumeb","Kuvukiland Block A","Yes","Yes","Yes","Partly privately owned","Leasehold","226","Decongested","Communal tap","Electricity",2),
    ("Oshikoto","Tsumeb","Kuvukiland Block B","Yes","No","No","Local Authority","Leasehold","9999","Congested","Communal tap","Electricity",2),
    ("Oshikoto","Tsumeb","Saamstaan","No","Yes","Yes","Local Authority","Leasehold","123","Decongested","None","Water, Sewer, Electricity",4),
    ("Oshikoto","Tsumeb","Soweto","No","Yes","Yes","Local Authority","Unknown","300","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Grootfontein","Omulunga Blikkies Dorp","Yes","Yes","No","Local Authority","Leasehold","811","Congested","Communal tap","Water",2),
    ("Otjozondjupa","Grootfontein","Kap en Bou","Yes","Yes","Yes","Local Authority","Starter","862","Congested","None","Not Applicable",1),
    ("Otjozondjupa","Grootfontein","Portions 81 and 82 Reception Area A","No","Yes","Yes","Local Authority","Starter","863","Congested","None","Not Applicable",1),
    ("Otjozondjupa","Grootfontein","Portions 81 and 82 Reception Area B","No","Yes","Yes","Local Authority","Starter","863","Congested","None","Not Applicable",1),
    ("Otjozondjupa","Okahandja","Ekunde 1","Yes","Yes","Yes","Local Authority","Leasehold","1014","Decongested","Communal tap","Not applicable",1),
    ("Otjozondjupa","Okahandja","Ekunde 2","Yes","Yes","Yes","Local Authority","Leasehold","861","Decongested","Communal tap","Not applicable",1),
    ("Otjozondjupa","Okahandja","Ekunde 3","Yes","Yes","Yes","Local Authority","Leasehold","1128","Congested","Communal tap","Not applicable",1),
    ("Otjozondjupa","Okahandja","Ekunde 6","Yes","Yes","Yes","Local Authority","Leasehold","331","Congested","Communal tap","Not applicable",1),
    ("Otjozondjupa","Okahandja","Vyf Rand Camp","Yes","Yes","Yes","Partly privately owned","Leasehold","824","Congested","Communal tap","Not applicable",1),
    ("Otjozondjupa","Okakarara","Ohakane","No","Yes","Yes","Local Authority","No Tenure Security","180","Congested","Unknown","Not Applicable",1),
    ("Otjozondjupa","Okakarara","Okakango 1 and 2 A","No","Yes","No","Local Authority","No Tenure Security","9999","Congested","Unknown","Not Applicable",1),
    ("Otjozondjupa","Okakarara","Okarui","No","No","No","Local Authority","No Tenure Security","9999","Decongested","Unknown","Not Applicable",1),
    ("Otjozondjupa","Okakarara","Oruindjoromakuja","No","Yes","Yes","Local Authority","No Tenure Security","234","Congested","Unknown","Not Applicable",1),
    ("Otjozondjupa","Okakarara","Ousaira","No","No","No","Local Authority","No Tenure Security","9999","Congested","Unknown","Water, Sewer, Electricity",4),
    ("Otjozondjupa","Otavi","Naruseb Camp","Yes","No","No","Partly privately owned","Leasehold","0","Congested","Communal tap","Water",2),
    ("Otjozondjupa","Otavi","New Cairo","Yes","Yes","Yes","Local Authority","Leasehold","414","Decongested","Communal tap","Water, Sewer, Electricity",4),
    ("Otjozondjupa","Otavi","Kap en Bou","Yes","No","Yes","Local Authority","Leasehold","705","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otavi","Harambee","Yes","No","No","Local Authority","Leasehold","0","Congested","Communal tap","Water",2),
    ("Otjozondjupa","Otavi","Otavi West Reception Area","Yes","Yes","Yes","Local Authority","Leasehold","582","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","DRC","Yes","Yes","Yes","Local Authority","Leasehold","1500","Congested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","New Ombili A","Yes","Yes","Yes","Local Authority","Leasehold","1000","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","New Ombili B","Yes","Yes","Yes","Local Authority","Leasehold","1000","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","New Ombili C","Yes","Yes","Yes","Local Authority","Leasehold","1000","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","Ombili","Yes","Yes","Yes","Local Authority","Leasehold","1400","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 16","Yes","Yes","Yes","Local Authority","Freehold","230","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 17","Yes","Yes","Yes","Local Authority","Freehold","197","Decongested","Communal tap","Water",2),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 19","Yes","Yes","Yes","Local Authority","Freehold","260","Congested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 21","Yes","Yes","Yes","Local Authority","Freehold","276","Congested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 22","Yes","Yes","Yes","Local Authority","Freehold","317","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 26","Yes","Yes","Yes","Local Authority","Freehold","276","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 27","Yes","Yes","Yes","Local Authority","Freehold","258","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Orwetoveni Extension 28","Yes","Yes","Yes","Local Authority","Freehold","282","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Otjiwarongo Extension 21","Yes","Yes","Yes","Local Authority","Freehold","321","Congested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Reception Area Phase 1","Yes","Yes","Yes","Local Authority","Freehold","800","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Reception Area Phase 2","Yes","Yes","Yes","Local Authority","Freehold","3500","Decongested","Communal tap","Not Applicable",1),
    ("Otjozondjupa","Otjiwarongo","Tsara Aibes","Yes","Yes","Yes","Local Authority","Leasehold","1000","Decongested","Communal tap","Water, Sewer",3),
    ("Zambezi","Bukalo","Mudaniko","No","No","No","Local Authority","No Tenure Security","0","Decongested","None","Not Applicable",1),
    ("Zambezi","Bukalo","Muleneni","No","No","No","Local Authority","No Tenure Security","0","Congested","Communal tap","Electricity",2),
    ("Zambezi","Bukalo","Shack Dweller Federation","No","Yes","No","Local Authority","Landhold","51","Decongested","Communal tap","Electricity",2),
    ("Zambezi","Katima Mulilo","Diary","No","No","No","Local Authority","No Tenure Security","1554","Congested","None","Not Applicable",1),
    ("Zambezi","Katima Mulilo","Makaravani West","No","No","No","Local Authority","No Tenure Security","9999","Congested","Communal tap","Not Applicable",1),
    ("Zambezi","Katima Mulilo","Nova","No","No","No","Local Authority","No Tenure Security","1857","Decongested","Communal tap","Water",2),
    ("Zambezi","Katima Mulilo","Lwayaha A","No","Yes","Yes","Local Authority","Freehold","185","Decongested","None","Water",2),
    ("Zambezi","Katima Mulilo","Lwayaha B","No","Yes","Yes","Local Authority","Freehold","185","Decongested","None","Water",2),
    ("Zambezi","Katima Mulilo","Shack Dwellers","Yes","Yes","Yes","Local Authority","Flexible Land Tenure","198","Decongested","None","Water, Electricity",3),
]

def load_all_settlements():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("DELETE FROM nhis_informal_settlements")
    date_loaded = datetime.now().strftime("%Y-%m-%d")
    for s in ALL_SETTLEMENTS:
        c.execute("""
            INSERT INTO nhis_informal_settlements 
            (region, local_authority, settlement_name, is_profiled, is_planned,
             is_surveyed, land_ownership, tenure_security, number_of_erven,
             congestion_status, communal_facilities, bulk_services, upgrade_level, date_loaded)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (*s, date_loaded))
    conn.commit()
    conn.close()
    print(f"Loaded {len(ALL_SETTLEMENTS)} national settlements into database.")

def print_national_summary():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    print("\n--- NATIONAL NHIS SUMMARY ---")
    c.execute("""
        SELECT region, COUNT(*) as total,
        SUM(CASE WHEN congestion_status='Congested' THEN 1 ELSE 0 END) as congested,
        ROUND(AVG(upgrade_level),1) as avg_level
        FROM nhis_informal_settlements
        GROUP BY region ORDER BY total DESC
    """)
    for r in c.fetchall():
        print(f"{r[0]}: {r[1]} settlements | {r[2]} congested | avg upgrade {r[3]}")
    
    print("\n--- ERONGO DETAIL (Your Coast) ---")
    c.execute("""
        SELECT local_authority, settlement_name, congestion_status, 
        bulk_services, upgrade_level 
        FROM nhis_informal_settlements 
        WHERE region='Erongo' ORDER BY local_authority
    """)
    for r in c.fetchall():
        print(f"  {r[0]} | {r[1]} | {r[2]} | {r[3]} | Level {r[4]}")
    conn.close()

if __name__ == "__main__":
    init_table()
    load_all_settlements()
    print_national_summary()
